user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /user

hub:
    resource: "@HubBundle/Resources/config/routing.xml"
    prefix:   /hub

web:
    resource: "@WebBundle/Resources/config/routing.xml"
    prefix:   /

app:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
