<?php

namespace Vma\Bundle\HubBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Vma\Domain\Account\Repository\UserRepositoryInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserRepositoryInterface
{
}
